#!/usr/bin/env bash

# Set environment variables for dev
export APP_PORT=${APP_PORT:-80}
export MYSQL_PORT=${DB_PORT:-3306}
export MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-secret}
export MYSQL_DATABASE=${MYSQL_DATABASE:-styde}
export MYSQL_USER=${MYSQL_USER:-styde} 
export MYSQL_PASSWORD=${MYSQL_PASSWORD:-secret}

COMPOSE="docker-compose"
PSRESULT=$(docker-compose ps -q)

if [ ! -z "$PSRESULT" ]; then
    EXEC="yes"
else
    EXEC="no"
fi

# If we pass any arguments...
if [ $# -gt 0 ]; then

    if [ -f .env ]; then
        source .env
    fi

    if [ "$1" == "start" ]; then
        $COMPOSE up -d
    elif [ "$1" == "stop" ]; then
        $COMPOSE down

    # If "art" is used, pass-thru to "artisan"
    # inside a new container
    elif [ "$1" == "artisan" ] || [ "$1" == "art" ]; then
        shift 1
        if [ "$EXEC" == "yes" ]; then
            $COMPOSE exec \
                app \
                php artisan "$@"
        else
            $COMPOSE run --rm \
                -w /var/www/html \
                app \
                php artisan "$@"
        fi

    # If "composer" is used, pass-thru to "composer"
    # inside a new container
    elif [ "$1" == "composer" ] || [ "$1" == "comp" ]; then
        shift 1
        if [ "$EXEC" == "yes" ]; then
            $COMPOSE exec \
                app \
                composer "$@"
        else
            $COMPOSE run --rm \
                -w /var/www/html \
                app \
                composer "$@"
        fi

    # If "test" is used, run unit tests,
    # pass-thru any extra arguments to php-unit
    elif [ "$1" == "test" ] || [ "$1" == "t" ]; then
        shift 1
        if [ "$EXEC" == "yes" ]; then
            $COMPOSE exec \
                app \
                ./vendor/bin/phpunit "$@"
        else
            $COMPOSE run --rm \
                -w /var/www/html \
                app \
                ./vendor/bin/phpunit "$@"
        fi

    # If "npm" is used, run npm
    # from our node container
    elif [ "$1" == "npm" ]; then
        shift 1
        $COMPOSE run --rm \
            -w /var/www/html \
            node \
            npm "$@"

    # If "gulp" is used, run gulp
    # from our node container
    elif [ "$1" == "gulp" ]; then
        shift 1
        $COMPOSE run --rm \
            -w /var/www/html \
            node \
            ./node_modules/.bin/gulp "$@"

    # If "yarn" is used, run yarn
    # from our node container
    elif [ "$1" == "yarn" ]; then
        shift 1
        $COMPOSE run --rm \
            -w /var/www/html \
            node \
            yarn "$@"

    # Else, pass-thru args to docker-compose
    else
        $COMPOSE "$@"
    fi
else
    $COMPOSE ps
fi
